name: React App CI/CD to Netlify

on:
  push:
    branches:
      - main # Trigger on every push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests for continuous integration checks

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests (CI Gate)
        run: npm test -- --watchAll=false # Ensures tests run once

      - name: Build React Application
        run: npm run build
        env:
          CI: false # Prevents CRA from treating warnings as errors during the build

      - name: Deploy to Netlify (CD)
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: 'build' # Default output directory for React build
          NETLIFY_DEPLOY_TO_PROD: true # Deploys to your live production URL